In [ ]:
import numpy as np

In [ ]:
a=np.arange(1,33,1).reshape(8,4)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [ ]:
b=np.random.rand(1)
print(b)


[0.39358406]


In [ ]:
b=np.random.rand(8,4)
print(b)

[[0.8305323  0.60081449 0.68514064 0.59953453]
 [0.95242903 0.94515685 0.51108765 0.92447972]
 [0.12231845 0.61932372 0.28980625 0.86194287]
 [0.04089409 0.38760558 0.99580987 0.45918126]
 [0.12949883 0.50270171 0.94958207 0.77229215]
 [0.46557434 0.25015119 0.45012221 0.91297065]
 [0.60778152 0.82263913 0.39049281 0.26534774]
 [0.37368251 0.54925933 0.24834007 0.58781189]]


In [ ]:
a=np.floor(10*np.random.rand(8,4))
print(a)

[[0. 3. 9. 3.]
 [3. 6. 2. 5.]
 [7. 3. 2. 6.]
 [2. 5. 0. 9.]
 [2. 3. 6. 8.]
 [9. 5. 1. 4.]
 [0. 2. 7. 2.]
 [9. 9. 5. 8.]]


In [ ]:
np.vsplit(a,4)


[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]]),
 array([[17, 18, 19, 20],
        [21, 22, 23, 24]]),
 array([[25, 26, 27, 28],
        [29, 30, 31, 32]])]

In [ ]:
#split after 3rd row and 5th column
np.vsplit(a,(3,5))

[array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16],
        [17, 18, 19, 20]]),
 array([[21, 22, 23, 24],
        [25, 26, 27, 28],
        [29, 30, 31, 32]])]

In [ ]:
b=np.arange(0,32,1).reshape(4,8)
print(b)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]]


In [ ]:
np.hsplit(b,(4,6))

[array([[ 0,  1,  2,  3],
        [ 8,  9, 10, 11],
        [16, 17, 18, 19],
        [24, 25, 26, 27]]),
 array([[ 4,  5],
        [12, 13],
        [20, 21],
        [28, 29]]),
 array([[ 6,  7],
        [14, 15],
        [22, 23],
        [30, 31]])]

In [ ]:
np.hsplit(b,(4,7))

[array([[ 0,  1,  2,  3],
        [ 8,  9, 10, 11],
        [16, 17, 18, 19],
        [24, 25, 26, 27]]),
 array([[ 4,  5,  6],
        [12, 13, 14],
        [20, 21, 22],
        [28, 29, 30]]),
 array([[ 7],
        [15],
        [23],
        [31]])]

trigonometry

In [ ]:
S=[np.pi/4,np.pi/3,np.pi/2,np.pi]
print(S)

[0.7853981633974483, 1.0471975511965976, 1.5707963267948966, 3.141592653589793]


In [ ]:
q=np.rad2deg(S)

In [ ]:

f=np.rad2deg(a)
print(f)

51.222235723088794


In [ ]:
a=np.sin(90)


NameError: name 'np' is not defined

In [ ]:
np.cos(0)

1.0

In [ ]:
st=np.array([23,45,67,89,21,34])
np.mean(st)

46.5

In [ ]:
np.median(st)

39.5

In [ ]:
#standard deviation
#variance
w=np.var(st)
print(w)
print(np.sqrt(w))

597.9166666666666
24.452334585202017


Linear algebra

In [ ]:
C=np.arange(1,5).reshape(2,2)
print(C)

[[1 2]
 [3 4]]


In [ ]:
np.linalg.inv(C)


array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [ ]:
c=np.arange(1,25).reshape(6,4)
print(c)
print(np.argmax(c,axis=0))
print(np.argmin(c,axis=1))


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
[5 5 5 5]
[0 0 0 0 0 0]


In [ ]:
t=10*np.random.rand(24).reshape(6,4)
print(t)
print(np.argmax(t))
print(np.argmin(t))

[[9.92609341 1.34111855 2.06958872 5.90793951]
 [0.11644706 3.92942076 4.15883163 9.21808961]
 [8.57589349 6.61327201 3.08975851 2.2909201 ]
 [5.88496464 0.36113344 2.81666714 5.91616593]
 [8.96162118 9.20139781 0.89099257 4.31005539]
 [3.79498501 0.53273736 4.03734868 5.72019127]]
0
4


searching

In [ ]:
a=np.array([34,56,7,17,36,91])
print(np.where(a%6 == 0))

[34 56  7 17 36 91]
(array([4]),)


In [ ]:
a=np.array([6,7,8,9,10])
print(np.searchsorted(a,10))

4


In [ ]:
a=np.array(["anil","harsha","nava","pavan","kp","shannu"])
print(np.sort(a))

['anil' 'harsha' 'kp' 'nava' 'pavan' 'shannu']


In [ ]:
print(np.searchsorted(a,'harsha'))

1


In [ ]:
h=np.array([[1,5,4],[8,2,0]])
print(h)

[[1 5 4]
 [8 2 0]]


In [ ]:
print(np.sort(h))

[[1 4 5]
 [0 2 8]]


In [ ]:
 e=np.array([48,25,46,89,78,12])
 b=np.where(e%2==0)
 print(b)
 e[b]

(array([0, 2, 4, 5]),)


array([48, 46, 78, 12])

In [ ]:
a=np.array(["jwalalitha","harsha","nitish","anil","jaya"])
inl=np.array(['k','p','w','q','u'])
for i,j in zip(inl,a):
  print(i,"-",j)

k - jwalalitha
p - harsha
w - nitish
q - anil
u - jaya


In [ ]:
s=np.array([2,3,4,5])
h=np.array([1,6,9,2])
n=np.multiply(s,h)
m=np.divide(s,h)
o=np.mod(s,h)
p=np.divmod(s,h)
print(n)
print(m)
print(o)
print(p)

[ 2 18 36 10]
[2.         0.5        0.44444444 2.5       ]
[0 3 4 1]
(array([2, 0, 0, 2]), array([0, 3, 4, 1]))


logarithms

In [ ]:
a=np.array([1,2,3,4,5])
print(np.log(a))
print(np.log2(a))
print(np.log10(a))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         1.         1.5849625  2.         2.32192809]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]


other mathematical functions

In [ ]:
q=np.array([5,6,7,16])
x=np.cumprod(q)
print(x)

[   5   30  210 3360]


In [ ]:
a=np.diff(q)
print(a)

[1 1 9]


In [ ]:
a=np.cumsum(q)
print(a)

[ 5 11 18 34]


In [ ]:
n=2
m=6
print(np.lcm(n,m))
print(np.gcd(n,m))

6
2


In [ ]:
a=np.array([12,15,60])
g=np.gcd.reduce(a)
print(g)

3
